name: Pascal Compiler CI

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flex bison libfl-dev libunwind-dev
        pip install meson ninja

    - name: Configure build
      run: meson setup builddir --buildtype=release

    - name: Build
      run: meson compile -C builddir

    - name: Run tests
      run: meson test -C builddir
