name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # Clone the repository to install dependencies
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison libfl-dev libunwind-dev libgmp-dev

      - name: Install Python build tools
        run: |
          pip install meson ninja

      - name: Configure build
        run: |
          meson setup builddir --buildtype=release -Dwith_gmp=enabled

      - name: Build project
        run: |
          meson compile -C builddir

      - name: Verify build outputs
        run: |
          ls -lh builddir/GPC/gpc
          ls -lh builddir/GPC/libgpc_runtime.a
