name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # Clone the repository to install dependencies
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison libfl-dev libunwind-dev libgmp-dev meson


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget tar zstd gawk gpg gpgv wine wine64 flex bison
          sudo apt-get install -y llvm clang lld

      - name: Clone quasi-msys2
        run: |
          git clone https://github.com/HolyBlackCat/quasi-msys2.git
          cd quasi-msys2
          echo "UCRT64" > msystem.txt

      - name: Install MSYS2 packages via quasi-msys2
        run: |
          cd quasi-msys2
          # Install GCC, GMP, and other required packages
          make install _gcc _gmp _meson _ninja _python 
        timeout-minutes: 30          

          


